#!/bin/bash

export PATH="/usr/local/bin:$PATH:/Users/andrew/Desktop/JanrainGithub/jr-config/bin"
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PYTHONPATH=/Users/andrew/Desktop/JanrainRepos/janrain-python-api:$PYTHONPATH
export JANRAIN_PARAMIKO_FALLBACK='yay'
alias ssh="ssh -l areder"

git_subdir() {
    BASE=$(git rev-parse --show-toplevel 2>/dev/null)

    if [[ -n "$BASE" ]] ; then
        SUB="\[\e[38;5;38m\]${PWD#$BASE}"
    else
        BASE="$PWD"
    fi

    echo "\[\e[38;5;25m\]$(tildefy "$BASE")$SUB\[\e[0m\]"
}

tildefy() {
    if [[ "$1" =~ ^"$HOME"(/|$) ]] ; then
        echo "~${1#$HOME}"
    else
        echo "$1"
    fi
}

jobs_sum() {
    local stopped=$(jobs -sp | wc -l | sed -e 's/^ *//' -e 's/ *$//')
    local running=$(jobs -rp | wc -l | sed -e 's/^ *//' -e 's/ *$//')
    if ((running+stopped)) ; then
        local out=
        if ((running)) ; then
            out=$out$running
        fi
        if ((running)) && ((stopped)) ; then
            out=$out,
        fi
        if ((stopped)) ; then
            out=$out'\[\e[38;5;88m\]'$stopped'\[\e[38;5;242m\]'
        fi
        echo '\[\e[38;5;242m\]'[$out]'\[\e[0m\]'
    fi
}

alias j=jobs
alias ccd="cd /Users/andrew/Desktop/JanrainRepos/CaptureCustomerDev"
alias cris="cd /Users/andrew/Desktop/CRISDev/meanCris"
alias avidphp="cd /Users/andrew/Desktop/Sites/AvidrederPHP"
alias avidng="cd /Users/andrew/Desktop/Sites/angular-avidreder"
alias deldash="cd /Users/andrew/Desktop/JanrainRepos/DelDash/delivery-dashboard"
alias ded="open -a 'Sublime Text 2'"
. /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
. /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM=1
GIT_PS1_SHOWCOLORHINTS=1
PROMPT_COMMAND='__git_ps1 "$(jobs_sum)\[\e[1;38;5;22m\]\u\[\e[0m\] $(git_subdir)" "\\\$ " " %s"'

complete -o default -W "3.dev-app.janraincapture.com 1.app.janraincapture.com pse.janrain.com 2.test-app.janraincapture.com 1.eu-app.janraincapture.com 1.au-app.janraincapture.com customer-dev.janrain.com capture-data-migration.janrain.com capture-data-migration-eu.janrain.com build.janraincapture.com capture-data-migration-au.janrain.com ubu1.local waldo.janrain.com" ssh sftp rby rtx
